"""TLDR.md generator — next-tokens a directory from indexed knowledge."""

from pathlib import Path
from . import rag
from .grapher import CodeGrapher
from .parser import parse_directory


def generate_claude_md(root: Path, output_dir: str = ".claude") -> Path:
    """Generate TLDR.md and TLDR_CONTEXT.md for a directory from TLDREADME's knowledge.

    This is the 'init' feature — TLDREADME has already indexed the code,
    now it serializes its understanding into files that bootstrap any LLM.
    """
    root = root.resolve()
    out = root / output_dir
    out.mkdir(exist_ok=True)

    grapher = CodeGrapher()

    # Get all modules under this root
    root_str = str(root)
    modules = _get_modules_under(grapher, root_str)

    # Generate TL;DR for each module
    module_summaries = {}
    for mod in modules[:20]:  # cap at 20 to avoid huge generation
        try:
            summary = rag.tldr(mod)
            module_summaries[mod] = summary
        except Exception:
            module_summaries[mod] = "(indexing pending)"

    # Build TLDR.md
    claude_md = _build_claude_md(root, modules, module_summaries)
    claude_path = out / "TLDR.md"
    claude_path.write_text(claude_md)

    # Build TLDR_CONTEXT.md (deeper)
    context_md = _build_context_md(root, grapher, modules)
    context_path = out / "TLDR_CONTEXT.md"
    context_path.write_text(context_md)

    return claude_path


def _get_modules_under(grapher: CodeGrapher, root: str) -> list[str]:
    """Get all indexed modules under a root path."""
    result = grapher.graph.query(
        "MATCH (m:Module) WHERE m.name STARTS WITH $root RETURN m.name ORDER BY m.name",
        {"root": root},
    )
    return [r[0] for r in result.result_set]


def _build_claude_md(root: Path, modules: list[str], summaries: dict[str, str]) -> str:
    """Build TLDR.md — the file that makes LLMs immediately productive."""
    lines = [
        f"# {root.name}",
        f"",
        f"*Auto-generated by TLDREADME. Last indexed: now.*",
        f"",
        f"## Overview",
        f"",
    ]

    # Top-level summary
    if summaries:
        first_key = next(iter(summaries))
        lines.append(summaries.get(str(root), summaries.get(first_key, "")))
        lines.append("")

    # Module map
    lines.append("## Modules")
    lines.append("")
    for mod in modules:
        rel = mod.replace(str(root) + "/", "")
        summary = summaries.get(mod, "")
        # First line of summary only
        one_liner = summary.split("\n")[0] if summary else ""
        lines.append(f"- **`{rel}/`** — {one_liner}")
    lines.append("")

    # Detailed summaries
    lines.append("## Module Details")
    lines.append("")
    for mod in modules:
        rel = mod.replace(str(root) + "/", "")
        summary = summaries.get(mod, "(not yet indexed)")
        lines.append(f"### {rel}")
        lines.append("")
        lines.append(summary)
        lines.append("")

    return "\n".join(lines)


def _build_context_md(root: Path, grapher: CodeGrapher, modules: list[str]) -> str:
    """Build TLDR_CONTEXT.md — deeper module map with symbols and relationships."""
    lines = [
        f"# {root.name} — Deep Context",
        f"",
        f"*Auto-generated by TLDREADME.*",
        f"",
    ]

    for mod in modules:
        rel = mod.replace(str(root) + "/", "")
        symbols = grapher.get_module_symbols(mod)
        if not symbols:
            continue

        lines.append(f"## {rel}")
        lines.append("")
        lines.append("| Symbol | Kind | Signature |")
        lines.append("|--------|------|-----------|")
        for s in symbols:
            lines.append(f"| `{s['name']}` | {s['kind']} | `{s['signature'][:80]}` |")
        lines.append("")

    return "\n".join(lines)
