"""Human-first roadmap helpers built on the existing planning bedrock."""

from datetime import datetime, timezone
from pathlib import Path
import re

AUTO_MARKER = "<!-- Auto-generated by TLDREADME roadmap -->"
HUMAN_OWNED_START = "<!-- HUMAN-OWNED: START -->"
HUMAN_OWNED_END = "<!-- HUMAN-OWNED: END -->"
AUTO_GENERATED_START = "<!-- AUTO-GENERATED: START -->"
AUTO_GENERATED_END = "<!-- AUTO-GENERATED: END -->"
PLANS_FILE = "TLDRPLANS.md"
PLANS_CAPTURE_PREFIX = "TLDRPLANS."
PLANS_CAPTURE_SUFFIX = ".md"
ROADMAP_FILE = "TLDROADMAP.md"
ROADMAP_DIR = Path(".tldr/roadmap")
BASELINE_PLANS_FILE = "baseline-tldrplans.md"


def _repo_root(root: str | Path = ".") -> Path:
    """Resolve a repository root path."""

    return Path(root).resolve()


def _work_root(root: str | Path = ".") -> Path:
    """Return the workboard root beneath the repository root."""

    return _repo_root(root) / ".tldr" / "work"


def _roadmap_dir(root: str | Path = ".") -> Path:
    """Return the roadmap planning directory."""

    return _repo_root(root) / ROADMAP_DIR


def _baseline_plans_path(root: str | Path = ".") -> Path:
    """Return the stored baseline plans path."""

    return _roadmap_dir(root) / BASELINE_PLANS_FILE


def _plans_path(root: str | Path = ".") -> Path:
    """Return the consolidated plans digest path."""

    return _roadmap_dir(root) / PLANS_FILE


def _roadmap_path(root: str | Path = ".") -> Path:
    """Return the durable roadmap path."""

    return _repo_root(root) / ROADMAP_FILE


def _notes_path(root: str | Path = ".") -> Path:
    """Return the tactical notes path."""

    return _repo_root(root) / "TLDRNOTES.md"


def _legacy_root_plans_path(root: str | Path = ".") -> Path:
    """Return the legacy root-level TLDRPLANS path."""

    return _repo_root(root) / PLANS_FILE


def _read_text(path: Path) -> str:
    """Read a UTF-8 file if it exists."""

    try:
        return path.read_text(encoding="utf-8").strip()
    except OSError:
        return ""


def _write_text(path: Path, text: str) -> None:
    """Write a UTF-8 file, creating parent directories."""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _timestamp() -> str:
    """Return a sortable UTC timestamp string."""

    return datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")


def _capture_filename(stamp: str | None = None) -> str:
    """Return a timestamped note-capture filename."""

    return f"{PLANS_CAPTURE_PREFIX}{stamp or _timestamp()}{PLANS_CAPTURE_SUFFIX}"


def _paragraphs(text: str) -> list[str]:
    """Split freeform Markdown into paragraphs."""

    return [chunk.strip() for chunk in re.split(r"\n\s*\n", text) if chunk.strip()]


def _flatten(paragraph: str) -> str:
    """Normalize a paragraph into one line."""

    return " ".join(line.strip() for line in paragraph.splitlines() if line.strip())


def _title_from_text(text: str, fallback: str) -> str:
    """Extract a short title from Markdown or prose."""

    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped.lstrip("#").strip() or fallback
    for paragraph in _paragraphs(text):
        flattened = _flatten(paragraph)
        if flattened:
            return flattened[:80]
    return fallback


def _excerpt(text: str, *, max_lines: int = 6, max_chars: int = 420) -> str:
    """Return a compact excerpt from freeform notes."""

    lines = [line.rstrip() for line in text.splitlines() if line.strip()]
    clipped = "\n".join(lines[:max_lines]).strip()
    if len(clipped) > max_chars:
        return clipped[: max_chars - 3].rstrip() + "..."
    return clipped


def _extract_urls(text: str) -> list[str]:
    """Return URLs mentioned in a blob of text."""

    return list(dict.fromkeys(re.findall(r"https?://[^\s)>]+", text)))


def _relative(path: Path, root: Path) -> str:
    """Render a repository-relative path when possible."""

    try:
        return str(path.resolve().relative_to(root))
    except Exception:
        return str(path)


def _markdown_title(text: str, fallback: str) -> str:
    """Extract the first heading-like title from markdown."""

    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped.lstrip("#").strip() or fallback
    return fallback


def _extract_marked_section(text: str, start_marker: str, end_marker: str) -> str:
    """Return the inner text for a marked section."""

    if start_marker not in text or end_marker not in text:
        return ""
    start = text.index(start_marker) + len(start_marker)
    end = text.index(end_marker, start)
    return text[start:end].strip()


def _default_human_owned_roadmap(root: str | Path = ".") -> str:
    """Return a starter human-owned roadmap section."""

    repo_root = _repo_root(root)
    intent = ""
    for text in [
        _read_text(repo_root / "README.md"),
        _read_text(repo_root / "GEMINI.md"),
        _read_text(_notes_path(repo_root)),
        _read_text(repo_root / "TLDREADME.md"),
    ]:
        for paragraph in _paragraphs(text):
            flattened = _flatten(paragraph)
            if (
                flattened
                and not flattened.startswith("#")
                and not flattened.startswith("|")
                and "```" not in flattened
                and len(flattened) >= 50
            ):
                intent = flattened
                break
        if intent:
            break
    if not intent:
        intent = "State the durable destination for this project here."
    return "\n".join(
        [
            "## North Star",
            "",
            intent,
            "",
            "## Strategic Direction",
            "",
            "- Keep this section human-owned.",
            "- State the durable destination, non-negotiable constraints, and major phases here.",
            "- Let the generated section below handle changing status, next options, and forecasts.",
        ]
    ).strip()


def _preserved_human_owned_roadmap(root: str | Path = ".") -> str:
    """Return the preserved human-owned roadmap section when present."""

    roadmap_text = _read_text(_roadmap_path(root))
    if not roadmap_text:
        return _default_human_owned_roadmap(root)

    preserved = _extract_marked_section(roadmap_text, HUMAN_OWNED_START, HUMAN_OWNED_END)
    if preserved:
        return preserved

    if AUTO_MARKER in roadmap_text:
        return _default_human_owned_roadmap(root)

    return roadmap_text.strip()


def _wrap_roadmap_document(human_owned: str, auto_generated: str) -> str:
    """Render the final roadmap document with explicit trust markers."""

    lines = [
        "# TLDROADMAP",
        "",
        HUMAN_OWNED_START,
        human_owned.strip(),
        HUMAN_OWNED_END,
        "",
        AUTO_GENERATED_START,
        auto_generated.strip(),
        AUTO_GENERATED_END,
    ]
    return "\n".join(lines).strip() + "\n"


def _capture_files(root: str | Path = ".") -> list[Path]:
    """Return timestamped plan-capture files, newest first."""

    plans_dir = _roadmap_dir(root)
    return sorted(plans_dir.glob(f"{PLANS_CAPTURE_PREFIX}*{PLANS_CAPTURE_SUFFIX}"), reverse=True)


def _baseline_plans_text(root: str | Path = ".") -> str:
    """Return preserved human-authored baseline plans text."""

    baseline_path = _baseline_plans_path(root)
    existing = _read_text(baseline_path)
    if existing:
        return existing

    current = _read_text(_plans_path(root))
    if current and AUTO_MARKER not in current:
        _write_text(baseline_path, current)
        return current

    legacy = _read_text(_legacy_root_plans_path(root))
    if legacy and AUTO_MARKER not in legacy:
        _write_text(baseline_path, legacy)
        return legacy

    if current and AUTO_MARKER in current:
        _write_text(baseline_path, current)
        return current
    return ""


def _intent_text(root: str | Path = ".") -> str:
    """Extract a human-facing project intent summary from root docs."""

    repo_root = _repo_root(root)
    candidates = [
        _read_text(repo_root / "README.md"),
        _preserved_human_owned_roadmap(repo_root),
        _read_text(_notes_path(repo_root)),
        _read_text(repo_root / "TLDREADME.md"),
        _read_text(repo_root / "GEMINI.md"),
    ]
    for text in candidates:
        for paragraph in _paragraphs(text):
            flattened = _flatten(paragraph)
            if (
                flattened
                and not flattened.startswith("#")
                and not flattened.startswith("|")
                and "```" not in flattened
                and len(flattened) >= 50
            ):
                return flattened
    return "No clear project intent paragraph was found. Fill out README.md with purpose, objectives, goals, current status, example repos, and links."


def _plans_digest(root: str | Path = ".") -> dict:
    """Return structured inputs from TLDRPLANS baseline and captured note files."""

    repo_root = _repo_root(root)
    baseline_text = _baseline_plans_text(repo_root)
    captures = []
    for path in _capture_files(repo_root):
        text = _read_text(path)
        captures.append(
            {
                "path": path.name,
                "title": _title_from_text(text, path.stem),
                "excerpt": _excerpt(text),
                "links": _extract_urls(text)[:5],
            }
        )
    return {
        "baseline_title": _title_from_text(baseline_text, "Baseline plans"),
        "baseline_excerpt": _excerpt(baseline_text) if baseline_text else "",
        "baseline_links": _extract_urls(baseline_text)[:5],
        "captures": captures,
    }


def read_plans_digest(root: str | Path = ".") -> dict:
    """Return the consolidated TLDRPLANS digest without mutating it."""

    repo_root = _repo_root(root)
    path = _plans_path(repo_root)
    text = _read_text(path)
    if not text:
        built = build_tldrplans(repo_root, write=False)
        text = built["markdown"]
    return {
        "path": str(path),
        "exists": path.exists(),
        "title": _markdown_title(text, PLANS_FILE),
        "content": text,
        "captures": _plans_digest(repo_root).get("captures", []),
    }


def read_notes(root: str | Path = ".") -> dict:
    """Return the tactical notes document for MCP/resource access."""

    path = _notes_path(root)
    text = _read_text(path)
    return {
        "path": str(path),
        "exists": path.exists(),
        "title": _markdown_title(text, "TLDRNOTES"),
        "content": text,
    }


def read_roadmap(root: str | Path = ".") -> dict:
    """Return the durable roadmap document, split by trust boundary when possible."""

    path = _roadmap_path(root)
    text = _read_text(path)
    human_owned = _extract_marked_section(text, HUMAN_OWNED_START, HUMAN_OWNED_END)
    auto_generated = _extract_marked_section(text, AUTO_GENERATED_START, AUTO_GENERATED_END)
    return {
        "path": str(path),
        "exists": path.exists(),
        "title": _markdown_title(text, "TLDROADMAP"),
        "content": text,
        "human_owned": human_owned,
        "auto_generated": auto_generated,
    }


def _progress_snapshot(root: str | Path = ".") -> dict:
    """Summarize tracked plan and task completion."""

    from .workboard import current_plan, get_plan, list_plans

    work_root = _work_root(root)
    listing = list_plans(root=work_root)
    current = current_plan(root=work_root)

    task_total = 0
    task_done = 0
    for summary in listing.get("plans", []):
        if summary.get("status") == "archived":
            continue
        plan = get_plan(summary["id"], root=work_root)
        for phase in plan.get("phases", []):
            for task in phase.get("tasks", []):
                task_total += 1
                if task.get("status") == "done":
                    task_done += 1

    percent = round((task_done / task_total) * 100, 1) if task_total else 0.0
    return {
        "plan_count": sum(1 for plan in listing.get("plans", []) if plan.get("status") != "archived"),
        "task_total": task_total,
        "task_done": task_done,
        "completion_percent": percent,
        "current": current,
    }


def build_tldrplans(root: str | Path = ".", *, write: bool = False) -> dict:
    """Consolidate baseline plans, note captures, and grounded goals into TLDRPLANS.md."""

    from .rag import suggest_goals

    repo_root = _repo_root(root)
    digest = _plans_digest(repo_root)
    goals = suggest_goals(str(repo_root))
    progress = _progress_snapshot(repo_root)
    current_summary = (progress.get("current") or {}).get("summary") or {}

    lines = [
        "# TLDRPLANS",
        "",
        AUTO_MARKER,
        "",
        f"Updated: {datetime.now(timezone.utc).replace(microsecond=0).isoformat()}",
        "",
    ]

    if digest["baseline_excerpt"]:
        lines.extend(
            [
                "## Baseline Intent",
                "",
                digest["baseline_excerpt"],
                "",
            ]
        )
        if digest["baseline_links"]:
            lines.append("Links:")
            lines.extend(f"- {link}" for link in digest["baseline_links"])
            lines.append("")

    lines.extend(
        [
            "## Grounded Next Goals",
            "",
            goals.get("suggested_goals", "No grounded goals were available."),
            "",
        ]
    )

    if current_summary:
        lines.extend(
            [
                "## Active Plan",
                "",
                f"- {current_summary.get('title')} [{current_summary.get('status')}]",
                "",
            ]
        )

    lines.extend(
        [
            "## Captured Planning Inputs",
            "",
        ]
    )
    captures = digest["captures"]
    if not captures:
        lines.append("No timestamped TLDRPLANS captures yet. Use `tldr plans-capture` to add one.")
        lines.append("")
    else:
        for capture in captures[:12]:
            lines.append(f"### {capture['path']}")
            lines.append("")
            if capture["excerpt"]:
                lines.append(capture["excerpt"])
                lines.append("")
            if capture["links"]:
                lines.append("Links:")
                lines.extend(f"- {link}" for link in capture["links"])
                lines.append("")

    markdown = "\n".join(lines).strip() + "\n"
    path = _plans_path(repo_root)
    if write:
        _write_text(path, markdown)

    return {
        "path": str(path),
        "markdown": markdown,
        "captures_count": len(captures),
        "captures": captures,
        "top_goal": goals.get("top_goal"),
        "candidate_goals": goals.get("candidate_goals", []),
        "current_plan": current_summary,
    }


def capture_plan_input(text: str, *, root: str | Path = ".") -> dict:
    """Persist a raw human planning dump and refresh TLDRPLANS.md."""

    repo_root = _repo_root(root)
    clean_text = text.strip()
    if not clean_text:
        raise ValueError("No planning input was provided.")

    capture_path = _roadmap_dir(repo_root) / _capture_filename()
    _write_text(capture_path, clean_text + "\n")
    consolidated = build_tldrplans(repo_root, write=True)
    return {
        "capture_path": str(capture_path),
        "plans_path": consolidated["path"],
        "captures_count": consolidated["captures_count"],
    }


def whats_next_vibe(root: str | Path = ".") -> dict:
    """Return a strategic roadmap snapshot for humans."""

    from .children import list_children
    from .coding_tools import repo_lookup, repo_next_action
    from .rag import best_question, suggest_goals
    from .summary import build_summary

    repo_root = _repo_root(root)
    plans = build_tldrplans(repo_root, write=False)
    goals = suggest_goals(str(repo_root))
    top_goal = goals.get("top_goal")
    question = best_question(top_goal, path=str(repo_root)) if top_goal else {}
    lookup = repo_lookup(query=top_goal, root=str(repo_root), limit=5) if top_goal else repo_lookup(root=str(repo_root), limit=5)
    next_action = repo_next_action(root=str(repo_root))
    summary = build_summary(root=repo_root, mark_checked=False, limit=5)
    progress = _progress_snapshot(repo_root)
    children = list_children(root=repo_root, include_ignored=True)
    scan = repo_lookup(root=str(repo_root), limit=5)

    direction_signals = []
    for hit in lookup.get("ranked_hits", [])[:5]:
        direction_signals.append(
            {
                "path": hit.get("path"),
                "line": hit.get("line"),
                "source_type": hit.get("source_type"),
                "snippet": hit.get("snippet"),
                "why_matched": hit.get("why_matched"),
            }
        )

    return {
        "project": repo_root.name,
        "project_intent": _intent_text(repo_root),
        "strategic_question": question.get("best_question"),
        "question_answer": question.get("answer"),
        "top_goal": top_goal,
        "next_options": goals.get("candidate_goals", [])[:3],
        "recommended_next_action": next_action.get("recommended_next_action") or goals.get("recommended_next_action"),
        "next_tool": next_action.get("suggested_tool"),
        "current_plan": (progress.get("current") or {}).get("summary"),
        "completion": {
            "percent": progress["completion_percent"],
            "tasks_done": progress["task_done"],
            "tasks_total": progress["task_total"],
            "plan_count": progress["plan_count"],
        },
        "current_code_status": {
            "source_counts": scan.get("source_counts", {}),
            "unknown_children": ((scan.get("children") or {}).get("unknown_count") or 0),
            "recent_counts": ((summary.get("counts") or {}) if summary else {}),
        },
        "direction_signals": direction_signals,
        "planning_inputs": {
            "plans_path": plans["path"],
            "captures_count": plans["captures_count"],
            "children_unknown": sum(1 for child in children.get("children", []) if child.get("status") == "unknown"),
        },
    }


def render_whats_next_vibe(payload: dict) -> str:
    """Render a concise human-facing whats-next report."""

    lines = [f"What's next for {payload['project']}", ""]
    lines.append(f"Intent: {payload.get('project_intent')}")
    lines.append("")

    completion = payload.get("completion") or {}
    lines.append(
        "Completion: "
        f"{completion.get('percent', 0.0)}% "
        f"({completion.get('tasks_done', 0)}/{completion.get('tasks_total', 0)} tasks across {completion.get('plan_count', 0)} plans)"
    )
    current_plan = payload.get("current_plan") or {}
    if current_plan:
        lines.append(f"Current plan: {current_plan.get('title')} [{current_plan.get('status')}]")

    source_counts = (payload.get("current_code_status") or {}).get("source_counts") or {}
    lines.append(
        "Current code status: "
        f"{source_counts.get('code', 0)} code, "
        f"{source_counts.get('tests', 0)} tests, "
        f"{source_counts.get('docs', 0)} docs, "
        f"{source_counts.get('workboard', 0)} workboard items"
    )
    lines.append("")

    if payload.get("strategic_question"):
        lines.append("Strategic question to ask now:")
        lines.append(payload["strategic_question"])
        lines.append("")

    if payload.get("top_goal"):
        lines.append(f"Top goal: {payload['top_goal']}")
        lines.append("")

    lines.append("Next options:")
    options = payload.get("next_options") or []
    if not options:
        lines.append("- No grounded options were available.")
    else:
        for candidate in options:
            files = ", ".join(candidate.get("files", [])[:3]) or "(scope pending)"
            lines.append(f"- {candidate['title']} - {candidate['why_now']} Files: {files}")
    lines.append("")

    lines.append(f"Recommended next action: {payload.get('recommended_next_action')}")
    if payload.get("next_tool"):
        lines.append(f"Next tool: {payload['next_tool']}")

    signals = payload.get("direction_signals") or []
    if signals:
        lines.append("")
        lines.append("Direction signals:")
        for signal in signals[:3]:
            location = signal["path"] or "(no path)"
            if signal.get("line"):
                location = f"{location}:{signal['line']}"
            snippet = (signal.get("snippet") or "").replace("\n", " ")
            lines.append(f"- [{signal.get('source_type')}] {location} - {snippet}")

    return "\n".join(lines).strip()


def render_current_vibe_roadmap(payload: dict) -> str:
    """Render the full TLDROADMAP.md document with a preserved human-owned section."""

    auto_lines = [
        AUTO_MARKER,
        "",
        f"Updated: {datetime.now(timezone.utc).replace(microsecond=0).isoformat()}",
        "",
        "## Project Intent",
        "",
        payload.get("project_intent") or "No project intent summary was available.",
        "",
        "## Strategic Question To Ask Now",
        "",
        payload.get("strategic_question") or "No strategic question was available.",
        "",
    ]

    if payload.get("question_answer"):
        auto_lines.extend(
            [
                "## Why That Question Matters",
                "",
                payload["question_answer"],
                "",
            ]
        )

    completion = payload.get("completion") or {}
    current_plan = payload.get("current_plan") or {}
    status = payload.get("current_code_status") or {}
    source_counts = status.get("source_counts") or {}
    auto_lines.extend(
        [
            "## Current Status",
            "",
            f"- Completion: {completion.get('percent', 0.0)}% ({completion.get('tasks_done', 0)}/{completion.get('tasks_total', 0)} tracked tasks)",
            f"- Plans in play: {completion.get('plan_count', 0)}",
            f"- Code/test/docs: {source_counts.get('code', 0)} / {source_counts.get('tests', 0)} / {source_counts.get('docs', 0)}",
            f"- Unknown children: {status.get('unknown_children', 0)}",
            f"- Current plan: {current_plan.get('title', 'none')} [{current_plan.get('status', 'n/a')}]",
            "",
        ]
    )

    auto_lines.extend(["## What's Next Options", ""])
    options = payload.get("next_options") or []
    if not options:
        auto_lines.append("- No grounded next options were available.")
    else:
        for index, candidate in enumerate(options, start=1):
            auto_lines.append(f"### Option {index}: {candidate['title']}")
            auto_lines.append("")
            auto_lines.append(candidate["goal"])
            auto_lines.append("")
            auto_lines.append(f"Why now: {candidate['why_now']}")
            if candidate.get("files"):
                auto_lines.append(f"Files: {', '.join(candidate['files'][:5])}")
            if candidate.get("verification_commands"):
                auto_lines.append("Verification:")
                auto_lines.extend(f"- `{command}`" for command in candidate["verification_commands"][:3])
            auto_lines.append("")

    signals = payload.get("direction_signals") or []
    auto_lines.extend(["## Direction Signals", ""])
    if not signals:
        auto_lines.append("No direction signals were available from repo lookup.")
        auto_lines.append("")
    else:
        for signal in signals[:5]:
            location = signal["path"] or "(no path)"
            if signal.get("line"):
                location = f"{location}:{signal['line']}"
            auto_lines.append(f"- [{signal.get('source_type')}] {location}")
            if signal.get("why_matched"):
                auto_lines.append(f"  why: {signal['why_matched']}")
            if signal.get("snippet"):
                auto_lines.append(f"  snippet: {signal['snippet'].replace(chr(10), ' ')}")
        auto_lines.append("")

    inputs = payload.get("planning_inputs") or {}
    auto_lines.extend(
        [
            "## Planning Inputs",
            "",
            f"- Plans digest: `{inputs.get('plans_path', str(_plans_path('.')))}`",
            f"- Captured note drops: {inputs.get('captures_count', 0)}",
            f"- Unknown child trees: {inputs.get('children_unknown', 0)}",
            f"- Recommended next action: {payload.get('recommended_next_action')}",
            "",
            "## Refresh Loop",
            "",
            "1. Use `tldr plans-capture` to drop fresh notes, links, and example-repo references.",
            "2. Run `tldr whats-next` to inspect the next strategic question and options.",
            "3. Run `tldr current-roadmap` to refresh this roadmap before or after each phase.",
            "",
        ]
    )

    human_owned = (payload.get("human_owned") or _default_human_owned_roadmap(".")).strip()
    return _wrap_roadmap_document(human_owned, "\n".join(auto_lines).strip())


def build_current_vibe_roadmap(root: str | Path = ".", *, write: bool = False) -> dict:
    """Build the current roadmap snapshot and optionally write TLDROADMAP.md."""

    repo_root = _repo_root(root)
    plans = build_tldrplans(repo_root, write=write)
    payload = whats_next_vibe(repo_root)
    payload["planning_inputs"]["plans_path"] = plans["path"]
    payload["human_owned"] = _preserved_human_owned_roadmap(repo_root)
    markdown = render_current_vibe_roadmap(payload)
    path = _roadmap_path(repo_root)
    if write:
        _write_text(path, markdown)
    payload["path"] = str(path)
    payload["markdown"] = markdown
    return payload
